---
################################
# Istio configMap cluster-wide
################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: mesh-config
  namespace: istio-system
data:
  mesh: |-
    initContainers:
    - name: istio-init
      image: "gcr.io/istio-testing/proxy_init:3101ea9d82a5f83b699c2d3245b371a19fa6bef4"  
      args: ["-p","15001", "-u", "1337"]
      imagePullPolicy: "IfNotPresent"
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
        priviledged: true
      restartPolicy: Always
    containers:
    - name: istio-proxy
      image: gcr.io/istio-testing/proxy_debug:3101ea9d82a5f83b699c2d3245b371a19fa6bef4
      args: 
      - proxy
      - sidecar
      - -v
      - "2"
      - --configPath
      - /etc/istio/proxy
      - --binaryPath
      - /usr/local/bin/envoy
      - --serviceCluster
      {{ if eq .ServiceCluster "" -}}
      - {{ "istio-proxy" }}
      {{ else -}}
      - {{ printf "%s" .ServiceCluster }}
      {{ end -}}
      - helloworld
      - --drainDuration
      - 45s
      - --parentShutdownDuration
      - 1m0s
      - --discoveryAddress
      - istio-pilot.istio-system:15003
      - --discoveryRefreshDelay
      - 1s
      - --zipkinAddress
      - zipkin.istio-system:9411
      - --connectTimeout
      - 10s
      - --statsdUdpAddress
      - istio-mixer.istio-system:9125
      - --proxyAdminPort
      - "15000"
      - --controlPlaneAuthPolicy
      - NONE
      env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: INSTANCE_IP
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      imagePullpolicy: IfNotPresent
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
        priviledged: true
      restartPolicy: Always
      volumeMounts:
      - mountPath: /etc/istio/proxy
        name: istio-envoy
      - mountPath: /etc/certs/
        name: istio-certs
        readOnly: true
    volumes:
    - emptyDir:
        medium: Memory
      name: istio-envoy
    - name: istio-certs
      secret:
        defaultMode: 420
        optional: true
        {{ if eq .Spec.ServiceAccountName "" -}}
        secretName: {{ "istio.default" }}
        {{ else -}}
        secretName: {{ printf "istio.%s" .Spec.ServiceAccountName }}
        {{ end -}}
